.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.2 */

/* Handwritten function */
nonmatching __osGetCause, 0xC

glabel __osGetCause
    /* A0A30 802E51F0 40026800 */  mfc0       $v0, $13 /* handwritten instruction */
    /* A0A34 802E51F4 03E00008 */  jr         $ra
    /* A0A38 802E51F8 00000000 */   nop
endlabel __osGetCause
    /* A0A3C 802E51FC 00000000 */  nop
