.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching D_hd_code_802C48A0

dlabel D_hd_code_802C48A0
    /* 800E0 802C48A0 802C48C4 */ .word D_hd_code_802C48C4
    /* 800E4 802C48A4 802C48D0 */ .word D_hd_code_802C48D0
    /* 800E8 802C48A8 802C48D8 */ .word D_hd_code_802C48D8
    /* 800EC 802C48AC 00000005 */ .word 0x00000005 /* invalid instruction */
    /* 800F0 802C48B0 01F4003C */ .word 0x01F4003C /* invalid instruction */
    /* 800F4 802C48B4 32140808 */ .word 0x32140808
    /* 800F8 802C48B8 E73201A0 */ .word 0xE73201A0
    /* 800FC 802C48BC 13FFFFFF */ .word 0x13FFFFFF
    /* 80100 802C48C0 FF000300 */ .word 0xFF000300
enddlabel D_hd_code_802C48A0

nonmatching D_hd_code_802C48C4

dlabel D_hd_code_802C48C4
    /* 80104 802C48C4 000407B9 */ .word 0x000407B9 /* invalid instruction */
    /* 80108 802C48C8 07BA07BB */ .word 0x07BA07BB /* invalid instruction */
    /* 8010C 802C48CC 07BC0000 */ .word 0x07BC0000 /* invalid instruction */
enddlabel D_hd_code_802C48C4

nonmatching D_hd_code_802C48D0

dlabel D_hd_code_802C48D0
    /* 80110 802C48D0 000207BD */ .word 0x000207BD /* invalid instruction */
    /* 80114 802C48D4 07BC0000 */ .word 0x07BC0000 /* invalid instruction */
enddlabel D_hd_code_802C48D0

nonmatching D_hd_code_802C48D8

dlabel D_hd_code_802C48D8
    /* 80118 802C48D8 001207BD */ .word 0x001207BD /* invalid instruction */
    /* 8011C 802C48DC 07BD07BD */ .word 0x07BD07BD /* invalid instruction */
    /* 80120 802C48E0 07BE07BE */ .word 0x07BE07BE /* invalid instruction */
    /* 80124 802C48E4 07BE07BF */ .word 0x07BE07BF /* invalid instruction */
    /* 80128 802C48E8 07BF07BF */ .word 0x07BF07BF /* invalid instruction */
    /* 8012C 802C48EC 07C007C0 */ .word 0x07C007C0
    /* 80130 802C48F0 07C007C1 */ .word 0x07C007C1
    /* 80134 802C48F4 07C107C1 */ .word 0x07C107C1
    /* 80138 802C48F8 07C207C2 */ .word 0x07C207C2
    /* 8013C 802C48FC 07C20000 */ .word 0x07C20000
enddlabel D_hd_code_802C48D8

nonmatching D_hd_code_802C4900

dlabel D_hd_code_802C4900
    /* 80140 802C4900 802C4924 */ .word D_hd_code_802C4924
    /* 80144 802C4904 802C4934 */ .word func_hd_code_802C4934
    /* 80148 802C4908 802C4938 */ .word D_hd_code_802C4938
    /* 8014C 802C490C 00000005 */ .word 0x00000005 /* invalid instruction */
    /* 80150 802C4910 0226003C */ .word 0x0226003C /* invalid instruction */
    /* 80154 802C4914 1E141010 */ .word 0x1E141010 /* invalid instruction */
    /* 80158 802C4918 E73201B4 */ .word 0xE73201B4
    /* 8015C 802C491C 13FFFFFF */ .word 0x13FFFFFF
    /* 80160 802C4920 FF000300 */ .word 0xFF000300
enddlabel D_hd_code_802C4900

nonmatching D_hd_code_802C4924

dlabel D_hd_code_802C4924
    /* 80164 802C4924 000607D0 */ .word 0x000607D0 /* invalid instruction */
    /* 80168 802C4928 07D007D1 */ .word 0x07D007D1
    /* 8016C 802C492C 07D107D2 */ .word 0x07D107D2
    /* 80170 802C4930 07D20000 */ .word 0x07D20000
enddlabel D_hd_code_802C4924

nonmatching func_hd_code_802C4934

dlabel func_hd_code_802C4934
    /* 80174 802C4934 000107D3 */ .word 0x000107D3 /* invalid instruction */
enddlabel func_hd_code_802C4934

nonmatching D_hd_code_802C4938

dlabel D_hd_code_802C4938
    /* 80178 802C4938 000707D4 */ .word 0x000707D4 /* invalid instruction */
    /* 8017C 802C493C 07D407D4 */ .word 0x07D407D4 /* invalid instruction */
    /* 80180 802C4940 07D407D4 */ .word 0x07D407D4 /* invalid instruction */
    /* 80184 802C4944 07D407D4 */ .word 0x07D407D4 /* invalid instruction */
enddlabel D_hd_code_802C4938

nonmatching D_hd_code_802C4948

dlabel D_hd_code_802C4948
    /* 80188 802C4948 802C496C */ .word D_hd_code_802C496C
    /* 8018C 802C494C 802C497C */ .word func_hd_code_802C497C
    /* 80190 802C4950 802C4980 */ .word D_hd_code_802C4980
    /* 80194 802C4954 00000005 */ .word 0x00000005 /* invalid instruction */
    /* 80198 802C4958 0190003C */ .word 0x0190003C /* invalid instruction */
    /* 8019C 802C495C 1E141010 */ .word 0x1E141010 /* invalid instruction */
    /* 801A0 802C4960 E73C01A0 */ .word 0xE73C01A0
    /* 801A4 802C4964 13FFFFFF */ .word 0x13FFFFFF
    /* 801A8 802C4968 FF000300 */ .word 0xFF000300
enddlabel D_hd_code_802C4948

nonmatching D_hd_code_802C496C

dlabel D_hd_code_802C496C
    /* 801AC 802C496C 000607D0 */ .word 0x000607D0 /* invalid instruction */
    /* 801B0 802C4970 07D007D1 */ .word 0x07D007D1
    /* 801B4 802C4974 07D107D2 */ .word 0x07D107D2
    /* 801B8 802C4978 07D20000 */ .word 0x07D20000
enddlabel D_hd_code_802C496C

nonmatching func_hd_code_802C497C

dlabel func_hd_code_802C497C
    /* 801BC 802C497C 000107D3 */ .word 0x000107D3 /* invalid instruction */
enddlabel func_hd_code_802C497C

nonmatching D_hd_code_802C4980

dlabel D_hd_code_802C4980
    /* 801C0 802C4980 000707D4 */ .word 0x000707D4 /* invalid instruction */
    /* 801C4 802C4984 07D407D4 */ .word 0x07D407D4 /* invalid instruction */
    /* 801C8 802C4988 07D407D4 */ .word 0x07D407D4 /* invalid instruction */
    /* 801CC 802C498C 07D407D4 */ .word 0x07D407D4 /* invalid instruction */
enddlabel D_hd_code_802C4980

nonmatching D_hd_code_802C4990

dlabel D_hd_code_802C4990
    /* 801D0 802C4990 802C49B4 */ .word D_hd_code_802C49B4
    /* 801D4 802C4994 802C49C4 */ .word func_hd_code_802C49C4
    /* 801D8 802C4998 802C49C8 */ .word D_hd_code_802C49C8
    /* 801DC 802C499C 00000005 */ .word 0x00000005 /* invalid instruction */
    /* 801E0 802C49A0 01F4003C */ .word 0x01F4003C /* invalid instruction */
    /* 801E4 802C49A4 1E141010 */ .word 0x1E141010 /* invalid instruction */
    /* 801E8 802C49A8 E73C01A0 */ .word 0xE73C01A0
    /* 801EC 802C49AC 13FFFFFF */ .word 0x13FFFFFF
    /* 801F0 802C49B0 FF000300 */ .word 0xFF000300
enddlabel D_hd_code_802C4990

nonmatching D_hd_code_802C49B4

dlabel D_hd_code_802C49B4
    /* 801F4 802C49B4 000607D0 */ .word 0x000607D0 /* invalid instruction */
    /* 801F8 802C49B8 07D007D1 */ .word 0x07D007D1
    /* 801FC 802C49BC 07D107D2 */ .word 0x07D107D2
    /* 80200 802C49C0 07D20000 */ .word 0x07D20000
enddlabel D_hd_code_802C49B4

nonmatching func_hd_code_802C49C4

dlabel func_hd_code_802C49C4
    /* 80204 802C49C4 000107D3 */ .word 0x000107D3 /* invalid instruction */
enddlabel func_hd_code_802C49C4

nonmatching D_hd_code_802C49C8

dlabel D_hd_code_802C49C8
    /* 80208 802C49C8 000707D4 */ .word 0x000707D4 /* invalid instruction */
    /* 8020C 802C49CC 07D407D4 */ .word 0x07D407D4 /* invalid instruction */
    /* 80210 802C49D0 07D407D4 */ .word 0x07D407D4 /* invalid instruction */
    /* 80214 802C49D4 07D407D4 */ .word 0x07D407D4 /* invalid instruction */
enddlabel D_hd_code_802C49C8

nonmatching D_hd_code_802C49D8

dlabel D_hd_code_802C49D8
    /* 80218 802C49D8 802C49FC */ .word D_hd_code_802C49FC
    /* 8021C 802C49DC 802C4A08 */ .word D_hd_code_802C4A08
    /* 80220 802C49E0 802C4A0C */ .word D_hd_code_802C4A0C
    /* 80224 802C49E4 00000005 */ .word 0x00000005 /* invalid instruction */
    /* 80228 802C49E8 01F4003C */ .word 0x01F4003C /* invalid instruction */
    /* 8022C 802C49EC 1E141010 */ .word 0x1E141010 /* invalid instruction */
    /* 80230 802C49F0 E73201A0 */ .word 0xE73201A0
    /* 80234 802C49F4 13FFFFFF */ .word 0x13FFFFFF
    /* 80238 802C49F8 FF000300 */ .word 0xFF000300
enddlabel D_hd_code_802C49D8

nonmatching D_hd_code_802C49FC

dlabel D_hd_code_802C49FC
    /* 8023C 802C49FC 00050848 */ .word 0x00050848 /* invalid instruction */
    /* 80240 802C4A00 08480848 */ .word 0x08480848
    /* 80244 802C4A04 08480848 */ .word 0x08480848
enddlabel D_hd_code_802C49FC

nonmatching D_hd_code_802C4A08

dlabel D_hd_code_802C4A08
    /* 80248 802C4A08 00010849 */ .word 0x00010849 /* invalid instruction */
enddlabel D_hd_code_802C4A08

nonmatching D_hd_code_802C4A0C

dlabel D_hd_code_802C4A0C
    /* 8024C 802C4A0C 0008084A */ .word 0x0008084A /* invalid instruction */
    /* 80250 802C4A10 084A084A */ .word 0x084A084A
    /* 80254 802C4A14 084A084B */ .word 0x084A084B
    /* 80258 802C4A18 084B084B */ .word 0x084B084B
    /* 8025C 802C4A1C 084B0000 */ .word 0x084B0000

nonmatching D_hd_code_802C4A20

dlabel D_hd_code_802C4A20
    /* 80260 802C4A20 802C48A0 */ .word D_hd_code_802C48A0
    /* 80264 802C4A24 802C4900 */ .word D_hd_code_802C4900
    /* 80268 802C4A28 802C4948 */ .word D_hd_code_802C4948
    /* 8026C 802C4A2C 802C4990 */ .word D_hd_code_802C4990
    /* 80270 802C4A30 802C49D8 */ .word D_hd_code_802C49D8
    /* 80274 802C4A34 FFFFFFFF */ .word 0xFFFFFFFF
    /* 80278 802C4A38 00000000 */ .word 0x00000000
    /* 8027C 802C4A3C 00000000 */ .word 0x00000000
enddlabel D_hd_code_802C4A0C
