.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

nonmatching bzero, 0x9C

glabel bzero
    /* 2EA0 80220BA0 28A1000C */  slti       $at, $a1, 0xC
    /* 2EA4 80220BA4 1420001D */  bnez       $at, .Linit_80220C1C
    /* 2EA8 80220BA8 00041823 */   negu      $v1, $a0
    /* 2EAC 80220BAC 30630003 */  andi       $v1, $v1, 0x3
    /* 2EB0 80220BB0 10600003 */  beqz       $v1, .Linit_80220BC0
    /* 2EB4 80220BB4 00A32823 */   subu      $a1, $a1, $v1
    /* 2EB8 80220BB8 A8800000 */  swl        $zero, 0x0($a0)
    /* 2EBC 80220BBC 00832021 */  addu       $a0, $a0, $v1
  .Linit_80220BC0:
    /* 2EC0 80220BC0 2401FFE0 */  addiu      $at, $zero, -0x20
    /* 2EC4 80220BC4 00A13824 */  and        $a3, $a1, $at
    /* 2EC8 80220BC8 10E0000C */  beqz       $a3, .Linit_80220BFC
    /* 2ECC 80220BCC 00A72823 */   subu      $a1, $a1, $a3
    /* 2ED0 80220BD0 00E43821 */  addu       $a3, $a3, $a0
  .Linit_80220BD4:
    /* 2ED4 80220BD4 24840020 */  addiu      $a0, $a0, 0x20
    /* 2ED8 80220BD8 AC80FFE0 */  sw         $zero, -0x20($a0)
    /* 2EDC 80220BDC AC80FFE4 */  sw         $zero, -0x1C($a0)
    /* 2EE0 80220BE0 AC80FFE8 */  sw         $zero, -0x18($a0)
    /* 2EE4 80220BE4 AC80FFEC */  sw         $zero, -0x14($a0)
    /* 2EE8 80220BE8 AC80FFF0 */  sw         $zero, -0x10($a0)
    /* 2EEC 80220BEC AC80FFF4 */  sw         $zero, -0xC($a0)
    /* 2EF0 80220BF0 AC80FFF8 */  sw         $zero, -0x8($a0)
    /* 2EF4 80220BF4 1487FFF7 */  bne        $a0, $a3, .Linit_80220BD4
    /* 2EF8 80220BF8 AC80FFFC */   sw        $zero, -0x4($a0)
  .Linit_80220BFC:
    /* 2EFC 80220BFC 2401FFFC */  addiu      $at, $zero, -0x4
    /* 2F00 80220C00 00A13824 */  and        $a3, $a1, $at
    /* 2F04 80220C04 10E00005 */  beqz       $a3, .Linit_80220C1C
    /* 2F08 80220C08 00A72823 */   subu      $a1, $a1, $a3
    /* 2F0C 80220C0C 00E43821 */  addu       $a3, $a3, $a0
  .Linit_80220C10:
    /* 2F10 80220C10 24840004 */  addiu      $a0, $a0, 0x4
    /* 2F14 80220C14 1487FFFE */  bne        $a0, $a3, .Linit_80220C10
    /* 2F18 80220C18 AC80FFFC */   sw        $zero, -0x4($a0)
  .Linit_80220C1C:
    /* 2F1C 80220C1C 18A00005 */  blez       $a1, .Linit_80220C34
    /* 2F20 80220C20 00000000 */   nop
    /* 2F24 80220C24 00A42821 */  addu       $a1, $a1, $a0
  .Linit_80220C28:
    /* 2F28 80220C28 24840001 */  addiu      $a0, $a0, 0x1
    /* 2F2C 80220C2C 1485FFFE */  bne        $a0, $a1, .Linit_80220C28
    /* 2F30 80220C30 A080FFFF */   sb        $zero, -0x1($a0)
  .Linit_80220C34:
    /* 2F34 80220C34 03E00008 */  jr         $ra
    /* 2F38 80220C38 00000000 */   nop
endlabel bzero
    /* 2F3C 80220C3C 00000000 */  nop
