.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.40.2 */

glabel func_init_80220730
    /* 2A30 80220730 27BDFFC0 */  addiu      $sp, $sp, -0x40
    /* 2A34 80220734 0C088310 */  jal        osInitialize
    /* 2A38 80220738 0080E025 */   or        $gp, $a0, $zero
    /* 2A3C 8022073C 3C050078 */  lui        $a1, %hi(D_787FD0)
    /* 2A40 80220740 3C07007E */  lui        $a3, %hi(D_7E3AD0)
    /* 2A44 80220744 24A57FD0 */  addiu      $a1, $a1, %lo(D_787FD0)
    /* 2A48 80220748 3C068000 */  lui        $a2, (0x80000400 >> 16)
    /* 2A4C 8022074C 24E73AD0 */  addiu      $a3, $a3, %lo(D_7E3AD0)
    /* 2A50 80220750 24040000 */  addiu      $a0, $zero, 0x0
    /* 2A54 80220754 34C60400 */  ori        $a2, $a2, (0x80000400 & 0xFFFF)
    /* 2A58 80220758 0C08839C */  jal        osPiRawStartDma
    /* 2A5C 8022075C 00E53822 */   sub       $a3, $a3, $a1 /* handwritten instruction */
  .Linit_80220760:
    /* 2A60 80220760 0C0883D4 */  jal        osPiGetStatus
    /* 2A64 80220764 00000000 */   nop
    /* 2A68 80220768 30420001 */  andi       $v0, $v0, 0x1
    /* 2A6C 8022076C 1440FFFC */  bnez       $v0, .Linit_80220760
    /* 2A70 80220770 00000000 */   nop
    /* 2A74 80220774 3C048000 */  lui        $a0, (0x80000400 >> 16)
    /* 2A78 80220778 3C058024 */  lui        $a1, (0x802447C0 >> 16)
    /* 2A7C 8022077C 3C06801E */  lui        $a2, (0x801E7000 >> 16)
    /* 2A80 80220780 34840400 */  ori        $a0, $a0, (0x80000400 & 0xFFFF)
    /* 2A84 80220784 34A547C0 */  ori        $a1, $a1, (0x802447C0 & 0xFFFF)
    /* 2A88 80220788 34C67000 */  ori        $a2, $a2, (0x801E7000 & 0xFFFF)
    /* 2A8C 8022078C 0C088266 */  jal        func_init_80220998
    /* 2A90 80220790 2407000D */   addiu     $a3, $zero, 0xD
    /* 2A94 80220794 0C088266 */  jal        func_init_80220998
    /* 2A98 80220798 2407000A */   addiu     $a3, $zero, 0xA
    /* 2A9C 8022079C 00A02025 */  or         $a0, $a1, $zero
    /* 2AA0 802207A0 3C058040 */  lui        $a1, (0x80400000 >> 16)
    /* 2AA4 802207A4 24060004 */  addiu      $a2, $zero, 0x4
  .Linit_802207A8:
    /* 2AA8 802207A8 AC800000 */  sw         $zero, 0x0($a0)
    /* 2AAC 802207AC 00862020 */  add        $a0, $a0, $a2 /* handwritten instruction */
    /* 2AB0 802207B0 1485FFFD */  bne        $a0, $a1, .Linit_802207A8
    /* 2AB4 802207B4 00000000 */   nop
    /* 2AB8 802207B8 3C04803F */  lui        $a0, (0x803FFFF8 >> 16)
    /* 2ABC 802207BC 3C05007E */  lui        $a1, %hi(D_7E3AD0)
    /* 2AC0 802207C0 3484FFF8 */  ori        $a0, $a0, (0x803FFFF8 & 0xFFFF)
    /* 2AC4 802207C4 24A53AD0 */  addiu      $a1, $a1, %lo(D_7E3AD0)
    /* 2AC8 802207C8 AC850000 */  sw         $a1, 0x0($a0)
    /* 2ACC 802207CC 3C04803F */  lui        $a0, (0x803FFFFC >> 16)
    /* 2AD0 802207D0 3C050080 */  lui        $a1, %hi(D_7F9BE0)
    /* 2AD4 802207D4 3484FFFC */  ori        $a0, $a0, (0x803FFFFC & 0xFFFF)
    /* 2AD8 802207D8 24A59BE0 */  addiu      $a1, $a1, %lo(D_7F9BE0)
    /* 2ADC 802207DC AC850000 */  sw         $a1, 0x0($a0)
    /* 2AE0 802207E0 27BDFF08 */  addiu      $sp, $sp, -0xF8
    /* 2AE4 802207E4 FFA40020 */  sd         $a0, 0x20($sp)
    /* 2AE8 802207E8 3C048022 */  lui        $a0, %hi(D_init_80222850)
    /* 2AEC 802207EC FFBF0000 */  sd         $ra, 0x0($sp)
    /* 2AF0 802207F0 24842850 */  addiu      $a0, $a0, %lo(D_init_80222850)
    /* 2AF4 802207F4 FFA10008 */  sd         $at, 0x8($sp)
    /* 2AF8 802207F8 FFA20010 */  sd         $v0, 0x10($sp)
    /* 2AFC 802207FC FFA30018 */  sd         $v1, 0x18($sp)
    /* 2B00 80220800 FFA50028 */  sd         $a1, 0x28($sp)
    /* 2B04 80220804 FFA60030 */  sd         $a2, 0x30($sp)
    /* 2B08 80220808 FFA70038 */  sd         $a3, 0x38($sp)
    /* 2B0C 8022080C FFA80040 */  sd         $t0, 0x40($sp)
    /* 2B10 80220810 FFA90048 */  sd         $t1, 0x48($sp)
    /* 2B14 80220814 FFAA0050 */  sd         $t2, 0x50($sp)
    /* 2B18 80220818 FFAB0058 */  sd         $t3, 0x58($sp)
    /* 2B1C 8022081C FFAC0060 */  sd         $t4, 0x60($sp)
    /* 2B20 80220820 FFAD0068 */  sd         $t5, 0x68($sp)
    /* 2B24 80220824 FFAE0070 */  sd         $t6, 0x70($sp)
    /* 2B28 80220828 FFAF0078 */  sd         $t7, 0x78($sp)
    /* 2B2C 8022082C FFB00080 */  sd         $s0, 0x80($sp)
    /* 2B30 80220830 FFB10088 */  sd         $s1, 0x88($sp)
    /* 2B34 80220834 FFB20090 */  sd         $s2, 0x90($sp)
    /* 2B38 80220838 FFB30098 */  sd         $s3, 0x98($sp)
    /* 2B3C 8022083C FFB400A0 */  sd         $s4, 0xA0($sp)
    /* 2B40 80220840 FFB500A8 */  sd         $s5, 0xA8($sp)
    /* 2B44 80220844 FFB600B0 */  sd         $s6, 0xB0($sp)
    /* 2B48 80220848 FFB700B8 */  sd         $s7, 0xB8($sp)
    /* 2B4C 8022084C FFB800C0 */  sd         $t8, 0xC0($sp)
    /* 2B50 80220850 FFB900C8 */  sd         $t9, 0xC8($sp)
    /* 2B54 80220854 FFBA00D0 */  sd         $k0, 0xD0($sp) /* handwritten instruction */
    /* 2B58 80220858 FFBB00D8 */  sd         $k1, 0xD8($sp) /* handwritten instruction */
    /* 2B5C 8022085C FFBC00E0 */  sd         $gp, 0xE0($sp)
    /* 2B60 80220860 FFBD00E8 */  sd         $sp, 0xE8($sp)
    /* 2B64 80220864 0C0881C5 */  jal        osSyncPrintf
    /* 2B68 80220868 FFBE00F0 */   sd        $fp, 0xF0($sp)
    /* 2B6C 8022086C DFBC00E0 */  ld         $gp, 0xE0($sp)
    /* 2B70 80220870 DFBF0000 */  ld         $ra, 0x0($sp)
    /* 2B74 80220874 DFA10008 */  ld         $at, 0x8($sp)
    /* 2B78 80220878 DFA20010 */  ld         $v0, 0x10($sp)
    /* 2B7C 8022087C DFA30018 */  ld         $v1, 0x18($sp)
    /* 2B80 80220880 DFA40020 */  ld         $a0, 0x20($sp)
    /* 2B84 80220884 DFA50028 */  ld         $a1, 0x28($sp)
    /* 2B88 80220888 DFA60030 */  ld         $a2, 0x30($sp)
    /* 2B8C 8022088C DFA70038 */  ld         $a3, 0x38($sp)
    /* 2B90 80220890 DFA80040 */  ld         $t0, 0x40($sp)
    /* 2B94 80220894 DFA90048 */  ld         $t1, 0x48($sp)
    /* 2B98 80220898 DFAA0050 */  ld         $t2, 0x50($sp)
    /* 2B9C 8022089C DFAB0058 */  ld         $t3, 0x58($sp)
    /* 2BA0 802208A0 DFAC0060 */  ld         $t4, 0x60($sp)
    /* 2BA4 802208A4 DFAD0068 */  ld         $t5, 0x68($sp)
    /* 2BA8 802208A8 DFAE0070 */  ld         $t6, 0x70($sp)
    /* 2BAC 802208AC DFAF0078 */  ld         $t7, 0x78($sp)
    /* 2BB0 802208B0 DFB00080 */  ld         $s0, 0x80($sp)
    /* 2BB4 802208B4 DFB10088 */  ld         $s1, 0x88($sp)
    /* 2BB8 802208B8 DFB20090 */  ld         $s2, 0x90($sp)
    /* 2BBC 802208BC DFB30098 */  ld         $s3, 0x98($sp)
    /* 2BC0 802208C0 DFB400A0 */  ld         $s4, 0xA0($sp)
    /* 2BC4 802208C4 DFB500A8 */  ld         $s5, 0xA8($sp)
    /* 2BC8 802208C8 DFB600B0 */  ld         $s6, 0xB0($sp)
    /* 2BCC 802208CC DFB700B8 */  ld         $s7, 0xB8($sp)
    /* 2BD0 802208D0 DFB800C0 */  ld         $t8, 0xC0($sp)
    /* 2BD4 802208D4 DFB900C8 */  ld         $t9, 0xC8($sp)
    /* 2BD8 802208D8 DFBA00D0 */  ld         $k0, 0xD0($sp) /* handwritten instruction */
    /* 2BDC 802208DC DFBB00D8 */  ld         $k1, 0xD8($sp) /* handwritten instruction */
    /* 2BE0 802208E0 DFBD00E8 */  ld         $sp, 0xE8($sp)
    /* 2BE4 802208E4 03802025 */  or         $a0, $gp, $zero
    /* 2BE8 802208E8 DFBE00F0 */  ld         $fp, 0xF0($sp)
    /* 2BEC 802208EC 27BD00F8 */  addiu      $sp, $sp, 0xF8
    /* 2BF0 802208F0 080911F0 */  j          func_802447C0
    /* 2BF4 802208F4 23BD0040 */   addi      $sp, $sp, 0x40 /* handwritten instruction */
endlabel func_init_80220730
    /* 2BF8 802208F8 00000000 */  nop
    /* 2BFC 802208FC 00000000 */  nop

glabel func_init_80220900
    /* 2C00 80220900 27BDFFA8 */  addiu      $sp, $sp, -0x58
    /* 2C04 80220904 FFBF0000 */  sd         $ra, 0x0($sp)
    /* 2C08 80220908 FFB00008 */  sd         $s0, 0x8($sp)
    /* 2C0C 8022090C FFB10010 */  sd         $s1, 0x10($sp)
    /* 2C10 80220910 FFB20018 */  sd         $s2, 0x18($sp)
    /* 2C14 80220914 FFB30020 */  sd         $s3, 0x20($sp)
    /* 2C18 80220918 FFB40028 */  sd         $s4, 0x28($sp)
    /* 2C1C 8022091C FFB50030 */  sd         $s5, 0x30($sp)
    /* 2C20 80220920 FFB60038 */  sd         $s6, 0x38($sp)
    /* 2C24 80220924 FFB70040 */  sd         $s7, 0x40($sp)
    /* 2C28 80220928 FFBC0048 */  sd         $gp, 0x48($sp)
    /* 2C2C 8022092C FFBE0050 */  sd         $fp, 0x50($sp)
    /* 2C30 80220930 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 2C34 80220934 FFBF0000 */  sd         $ra, 0x0($sp)
    /* 2C38 80220938 FFA40008 */  sd         $a0, 0x8($sp)
    /* 2C3C 8022093C FFA50010 */  sd         $a1, 0x10($sp)
    /* 2C40 80220940 8C840000 */  lw         $a0, 0x0($a0)
    /* 2C44 80220944 0C088294 */  jal        func_init_80220A50
    /* 2C48 80220948 8CA50000 */   lw        $a1, 0x0($a1)
    /* 2C4C 8022094C DFAE0008 */  ld         $t6, 0x8($sp)
    /* 2C50 80220950 DFAF0010 */  ld         $t7, 0x10($sp)
    /* 2C54 80220954 DFBF0000 */  ld         $ra, 0x0($sp)
    /* 2C58 80220958 ADC40000 */  sw         $a0, 0x0($t6)
    /* 2C5C 8022095C 27BD0018 */  addiu      $sp, $sp, 0x18
    /* 2C60 80220960 ADE50000 */  sw         $a1, 0x0($t7)
    /* 2C64 80220964 DFBF0000 */  ld         $ra, 0x0($sp)
    /* 2C68 80220968 DFBE0050 */  ld         $fp, 0x50($sp)
    /* 2C6C 8022096C DFBC0048 */  ld         $gp, 0x48($sp)
    /* 2C70 80220970 DFB70040 */  ld         $s7, 0x40($sp)
    /* 2C74 80220974 DFB60038 */  ld         $s6, 0x38($sp)
    /* 2C78 80220978 DFB50030 */  ld         $s5, 0x30($sp)
    /* 2C7C 8022097C DFB40028 */  ld         $s4, 0x28($sp)
    /* 2C80 80220980 DFB30020 */  ld         $s3, 0x20($sp)
    /* 2C84 80220984 DFB20018 */  ld         $s2, 0x18($sp)
    /* 2C88 80220988 DFB10010 */  ld         $s1, 0x10($sp)
    /* 2C8C 8022098C DFB00008 */  ld         $s0, 0x8($sp)
    /* 2C90 80220990 03E00008 */  jr         $ra
    /* 2C94 80220994 27BD0058 */   addiu     $sp, $sp, 0x58
endlabel func_init_80220900

glabel func_init_80220998
    /* 2C98 80220998 27BDFFA8 */  addiu      $sp, $sp, -0x58
    /* 2C9C 8022099C 3C018022 */  lui        $at, %hi(D_init_80224A30)
    /* 2CA0 802209A0 FFBF0000 */  sd         $ra, 0x0($sp)
    /* 2CA4 802209A4 FFB00008 */  sd         $s0, 0x8($sp)
    /* 2CA8 802209A8 FFB10010 */  sd         $s1, 0x10($sp)
    /* 2CAC 802209AC FFB20018 */  sd         $s2, 0x18($sp)
    /* 2CB0 802209B0 FFB30020 */  sd         $s3, 0x20($sp)
    /* 2CB4 802209B4 FFB40028 */  sd         $s4, 0x28($sp)
    /* 2CB8 802209B8 FFB50030 */  sd         $s5, 0x30($sp)
    /* 2CBC 802209BC FFB60038 */  sd         $s6, 0x38($sp)
    /* 2CC0 802209C0 FFB70040 */  sd         $s7, 0x40($sp)
    /* 2CC4 802209C4 FFBC0048 */  sd         $gp, 0x48($sp)
    /* 2CC8 802209C8 FFBE0050 */  sd         $fp, 0x50($sp)
    /* 2CCC 802209CC AC244A30 */  sw         $a0, %lo(D_init_80224A30)($at)
    /* 2CD0 802209D0 23BDFF80 */  addi       $sp, $sp, -0x80 /* handwritten instruction */
    /* 2CD4 802209D4 3C018022 */  lui        $at, %hi(D_init_80224A34)
    /* 2CD8 802209D8 AC254A34 */  sw         $a1, %lo(D_init_80224A34)($at)
    /* 2CDC 802209DC 27BDFFF0 */  addiu      $sp, $sp, -0x10
    /* 2CE0 802209E0 3C048022 */  lui        $a0, %hi(D_init_80224A30)
    /* 2CE4 802209E4 3C058022 */  lui        $a1, %hi(D_init_80224A34)
    /* 2CE8 802209E8 FFBF0000 */  sd         $ra, 0x0($sp)
    /* 2CEC 802209EC 24844A30 */  addiu      $a0, $a0, %lo(D_init_80224A30)
    /* 2CF0 802209F0 24A54A34 */  addiu      $a1, $a1, %lo(D_init_80224A34)
    /* 2CF4 802209F4 0C0880D8 */  jal        func_init_80220360
    /* 2CF8 802209F8 FFA60008 */   sd        $a2, 0x8($sp)
    /* 2CFC 802209FC DFBF0000 */  ld         $ra, 0x0($sp)
    /* 2D00 80220A00 DFA60008 */  ld         $a2, 0x8($sp)
    /* 2D04 80220A04 3C048022 */  lui        $a0, %hi(D_init_80224A30)
    /* 2D08 80220A08 3C058022 */  lui        $a1, %hi(D_init_80224A34)
    /* 2D0C 80220A0C 27BD0010 */  addiu      $sp, $sp, 0x10
    /* 2D10 80220A10 8C844A30 */  lw         $a0, %lo(D_init_80224A30)($a0)
    /* 2D14 80220A14 8CA54A34 */  lw         $a1, %lo(D_init_80224A34)($a1)
    /* 2D18 80220A18 23BD0080 */  addi       $sp, $sp, 0x80 /* handwritten instruction */
    /* 2D1C 80220A1C DFBF0000 */  ld         $ra, 0x0($sp)
    /* 2D20 80220A20 DFB00008 */  ld         $s0, 0x8($sp)
    /* 2D24 80220A24 DFB10010 */  ld         $s1, 0x10($sp)
    /* 2D28 80220A28 DFB20018 */  ld         $s2, 0x18($sp)
    /* 2D2C 80220A2C DFB30020 */  ld         $s3, 0x20($sp)
    /* 2D30 80220A30 DFB40028 */  ld         $s4, 0x28($sp)
    /* 2D34 80220A34 DFB50030 */  ld         $s5, 0x30($sp)
    /* 2D38 80220A38 DFB60038 */  ld         $s6, 0x38($sp)
    /* 2D3C 80220A3C DFB70040 */  ld         $s7, 0x40($sp)
    /* 2D40 80220A40 DFBC0048 */  ld         $gp, 0x48($sp)
    /* 2D44 80220A44 DFBE0050 */  ld         $fp, 0x50($sp)
    /* 2D48 80220A48 03E00008 */  jr         $ra
    /* 2D4C 80220A4C 27BD0058 */   addiu     $sp, $sp, 0x58
endlabel func_init_80220998

glabel func_init_80220A50
    /* 2D50 80220A50 24150001 */  addiu      $s5, $zero, 0x1
    /* 2D54 80220A54 240E000F */  addiu      $t6, $zero, 0xF
    /* 2D58 80220A58 01C77023 */  subu       $t6, $t6, $a3
    /* 2D5C 80220A5C 00F58004 */  sllv       $s0, $s5, $a3
    /* 2D60 80220A60 27BDFFF8 */  addiu      $sp, $sp, -0x8
    /* 2D64 80220A64 24140080 */  addiu      $s4, $zero, 0x80
    /* 2D68 80220A68 00F53823 */  subu       $a3, $a3, $s5
    /* 2D6C 80220A6C FFBF0000 */  sd         $ra, 0x0($sp)
    /* 2D70 80220A70 24160002 */  addiu      $s6, $zero, 0x2
    /* 2D74 80220A74 00005825 */  or         $t3, $zero, $zero
    /* 2D78 80220A78 02806025 */  or         $t4, $s4, $zero
    /* 2D7C 80220A7C 02A04825 */  or         $t1, $s5, $zero
    /* 2D80 80220A80 01D57004 */  sllv       $t6, $s5, $t6
    /* 2D84 80220A84 02158023 */  subu       $s0, $s0, $s5
    /* 2D88 80220A88 00F56804 */  sllv       $t5, $s5, $a3
  .Linit_80220A8C:
    /* 2D8C 80220A8C 15940003 */  bne        $t4, $s4, .Linit_80220A9C
    /* 2D90 80220A90 00000000 */   nop
    /* 2D94 80220A94 908B0000 */  lbu        $t3, 0x0($a0)
    /* 2D98 80220A98 00952021 */  addu       $a0, $a0, $s5
  .Linit_80220A9C:
    /* 2D9C 80220A9C 016CB824 */  and        $s7, $t3, $t4
    /* 2DA0 80220AA0 02AC6006 */  srlv       $t4, $t4, $s5
    /* 2DA4 80220AA4 15800002 */  bnez       $t4, .Linit_80220AB0
    /* 2DA8 80220AA8 00000000 */   nop
    /* 2DAC 80220AAC 02806025 */  or         $t4, $s4, $zero
  .Linit_80220AB0:
    /* 2DB0 80220AB0 12E0000A */  beqz       $s7, .Linit_80220ADC
    /* 2DB4 80220AB4 00000000 */   nop
    /* 2DB8 80220AB8 0C0882D7 */  jal        func_init_80220B5C
    /* 2DBC 80220ABC 02803825 */   or        $a3, $s4, $zero
    /* 2DC0 80220AC0 00C9B821 */  addu       $s7, $a2, $t1
    /* 2DC4 80220AC4 A0A20000 */  sb         $v0, 0x0($a1)
    /* 2DC8 80220AC8 01354821 */  addu       $t1, $t1, $s5
    /* 2DCC 80220ACC 00B52821 */  addu       $a1, $a1, $s5
    /* 2DD0 80220AD0 A2E20000 */  sb         $v0, 0x0($s7)
    /* 2DD4 80220AD4 1000FFED */  b          .Linit_80220A8C
    /* 2DD8 80220AD8 01304824 */   and       $t1, $t1, $s0
  .Linit_80220ADC:
    /* 2DDC 80220ADC 0C0882D7 */  jal        func_init_80220B5C
    /* 2DE0 80220AE0 01A03825 */   or        $a3, $t5, $zero
    /* 2DE4 80220AE4 10400015 */  beqz       $v0, .Linit_80220B3C
    /* 2DE8 80220AE8 00000000 */   nop
    /* 2DEC 80220AEC 00404025 */  or         $t0, $v0, $zero
    /* 2DF0 80220AF0 0C0882D7 */  jal        func_init_80220B5C
    /* 2DF4 80220AF4 01C03825 */   or        $a3, $t6, $zero
    /* 2DF8 80220AF8 0056C821 */  addu       $t9, $v0, $s6
    /* 2DFC 80220AFC 0000B825 */  or         $s7, $zero, $zero
  .Linit_80220B00:
    /* 2E00 80220B00 0117C021 */  addu       $t8, $t0, $s7
    /* 2E04 80220B04 0310C024 */  and        $t8, $t8, $s0
    /* 2E08 80220B08 00D8C021 */  addu       $t8, $a2, $t8
    /* 2E0C 80220B0C 93180000 */  lbu        $t8, 0x0($t8)
    /* 2E10 80220B10 00C95021 */  addu       $t2, $a2, $t1
    /* 2E14 80220B14 02F5B821 */  addu       $s7, $s7, $s5
    /* 2E18 80220B18 01354821 */  addu       $t1, $t1, $s5
    /* 2E1C 80220B1C 0337082A */  slt        $at, $t9, $s7
    /* 2E20 80220B20 A0B80000 */  sb         $t8, 0x0($a1)
    /* 2E24 80220B24 00B52821 */  addu       $a1, $a1, $s5
    /* 2E28 80220B28 01304824 */  and        $t1, $t1, $s0
    /* 2E2C 80220B2C 1020FFF4 */  beqz       $at, .Linit_80220B00
    /* 2E30 80220B30 A1580000 */   sb        $t8, 0x0($t2)
    /* 2E34 80220B34 1000FFD5 */  b          .Linit_80220A8C
    /* 2E38 80220B38 00000000 */   nop
  .Linit_80220B3C:
    /* 2E3C 80220B3C 0095B824 */  and        $s7, $a0, $s5
    /* 2E40 80220B40 12E00002 */  beqz       $s7, .Linit_80220B4C
    /* 2E44 80220B44 00000000 */   nop
    /* 2E48 80220B48 00952020 */  add        $a0, $a0, $s5 /* handwritten instruction */
  .Linit_80220B4C:
    /* 2E4C 80220B4C DFBF0000 */  ld         $ra, 0x0($sp)
    /* 2E50 80220B50 27BD0008 */  addiu      $sp, $sp, 0x8
    /* 2E54 80220B54 03E00008 */  jr         $ra
    /* 2E58 80220B58 00000000 */   nop
endlabel func_init_80220A50

glabel func_init_80220B5C
    /* 2E5C 80220B5C 00001025 */  or         $v0, $zero, $zero
  .Linit_80220B60:
    /* 2E60 80220B60 15940003 */  bne        $t4, $s4, .Linit_80220B70
    /* 2E64 80220B64 00000000 */   nop
    /* 2E68 80220B68 908B0000 */  lbu        $t3, 0x0($a0)
    /* 2E6C 80220B6C 00952021 */  addu       $a0, $a0, $s5
  .Linit_80220B70:
    /* 2E70 80220B70 016CB824 */  and        $s7, $t3, $t4
    /* 2E74 80220B74 12E00002 */  beqz       $s7, .Linit_80220B80
    /* 2E78 80220B78 00000000 */   nop
    /* 2E7C 80220B7C 00471025 */  or         $v0, $v0, $a3
  .Linit_80220B80:
    /* 2E80 80220B80 000C6042 */  srl        $t4, $t4, 1
    /* 2E84 80220B84 15800002 */  bnez       $t4, .Linit_80220B90
    /* 2E88 80220B88 00073842 */   srl       $a3, $a3, 1
    /* 2E8C 80220B8C 02806025 */  or         $t4, $s4, $zero
  .Linit_80220B90:
    /* 2E90 80220B90 14E0FFF3 */  bnez       $a3, .Linit_80220B60
    /* 2E94 80220B94 00000000 */   nop
    /* 2E98 80220B98 03E00008 */  jr         $ra
    /* 2E9C 80220B9C 00000000 */   nop
endlabel func_init_80220B5C

.section .data, "wa"

/* Generated by spimdisasm 1.40.2 */

.align 2
nonmatching D_init_80222850

dlabel D_init_80222850
    /* 4B50 80222850 */ .asciz "got here 2\n"
    /* 676F74206865726520320A00 */
.align 2
.align 2
    /* 4B5C 8022285C */ .asciz ""
    /* 00000000 */
.align 2
enddlabel D_init_80222850
