#!/usr/bin/env python3
"""
Reads decompressed/decompressed.map and emits a linker script (exported_symbols.auto.txt)
that re-expresses every hd_code/hd_front_end symbol -- both compiled functions/data and
the section-boundary bookkeeping symbols (hd_code_bss_VRAM, hd_code_DATA_START,
hd_code_TEXT_SIZE, ...) -- relative to hd_code_VRAM / hd_front_end_VRAM, instead of the
absolute address decompressed.map happened to link at.

hd_code_VRAM and hd_front_end_VRAM are themselves computed elsewhere (see
undefined_syms.init.<version>.txt) from the parent build's actual init size, so any
symbol expressed relative to them tracks that shift automatically instead of going
stale when init grows or shrinks. *_SIZE symbols (byte counts, e.g.
hd_code_TEXT_SIZE = ABSOLUTE(END - START)) are position-independent by construction and
are emitted as plain literals. *_ROM_START/*_ROM_END are dropped: they describe this
submodule's own standalone ROM layout, which has no relationship to where the parent
build embeds hd_code's compressed blob.

Run after every decompressed/ build (wired into decompressed/Makefile).
"""

import argparse
import re
import sys
from pathlib import Path

# Which top-level output sections to pull symbols from, and which root symbol
# (already defined relative to init_VRAM_END elsewhere) each family is offset from.
FAMILY_ROOTS = {
    "hd_code": "hd_code_VRAM",
    "hd_code_bss": "hd_code_VRAM",
    "hd_front_end": "hd_front_end_VRAM",
    "hd_front_end_bss": "hd_front_end_VRAM",
}

SECTION_HEADER_RE = re.compile(r"^\.(\S+)")
ROOT_ADDR_RE = re.compile(
    r"^\s+0x([0-9a-fA-F]{16})\s+(\S+)\s*=\s*ADDR\s*\(\.(\S+)\)\s*$"
)
# A defined address (bare "0xADDR name") or an assignment ("0xADDR name = RHS").
SYMBOL_RE = re.compile(r"^\s+0x([0-9a-fA-F]{16})\s+(\S+)(?:\s*=\s*(.*))?$")


def parse_map(map_path: Path):
    root_addrs = {}  # "hd_code" / "hd_front_end" -> int
    # root_symbol -> name -> ("addr", offset_int) | ("size", value_int)
    symbols = {root: {} for root in set(FAMILY_ROOTS.values())}
    current_section = None

    with map_path.open() as f:
        for line in f:
            line = line.rstrip("\n")
            if not line.strip():
                continue

            m = ROOT_ADDR_RE.match(line)
            if m:
                addr, _name, section = m.group(1), m.group(2), m.group(3)
                if section in ("hd_code", "hd_front_end"):
                    root_addrs[section] = int(addr, 16)
                if section in FAMILY_ROOTS:
                    # "<name>_VRAM = ADDR (.<name>)" precedes its own section
                    # header by a few lines (interleaved with ROM-offset
                    # bookkeeping like "__romPos = ..." that belongs to
                    # neither the old nor the new family). Without this, the
                    # next few lines -- including this one -- would still be
                    # attributed to whatever section came before it.
                    current_section = section
                # fall through: still handled generically below (captures
                # e.g. hd_code_bss_VRAM as an offset from hd_code_VRAM; the
                # family's own root, e.g. hd_code_VRAM itself, is skipped
                # there by the "name == root_symbol" guard).

            # Top-level output section headers start at column 0 (".hd_code",
            # ".hd_code_bss", possibly with the address wrapped to the next
            # line if the name is long, e.g. ".hd_front_end_bss").
            if not line[0].isspace():
                hm = SECTION_HEADER_RE.match(line)
                current_section = hm.group(1) if hm else None
                continue

            if current_section not in FAMILY_ROOTS:
                continue

            m = SYMBOL_RE.match(line)
            if not m:
                continue
            addr, name, rhs = int(m.group(1), 16), m.group(2), m.group(3)

            if rhs is not None:
                if name == ".":
                    continue  # location-counter bump, not a real symbol
                if name == "__romPos" or name.endswith("_ROM_START") or name.endswith("_ROM_END"):
                    continue  # ROM-file-offset space, meaningless in the parent build
                kind = "size" if "ABSOLUTE" in rhs else "addr"
            else:
                kind = "addr"

            root_symbol = FAMILY_ROOTS[current_section]
            if name == root_symbol:
                continue  # e.g. hd_code_VRAM itself -- defined elsewhere, would self-reference
            # First definition wins; a real link can't have produced two
            # addresses for the same global symbol.
            symbols[root_symbol].setdefault(name, (kind, addr))

    return root_addrs, symbols


def render(root_addrs, symbols) -> str:
    out = [
        "/* Auto-generated by tools/gen_exported_symbols.py from decompressed.map. */",
        "/* Do not edit by hand -- regenerated after every decompressed/ build. */",
        "",
    ]

    # PROVIDE(), not a plain assignment: some of these names (shared
    # libultra/runtime routines like osInitialize, bzero, __ll_mul) are ALSO
    # linked directly into other overlays. A plain assignment would silently
    # override their real address; PROVIDE only takes effect if nothing else
    # already defines the symbol. This also makes it safe for
    # hd_code_VRAM/hd_front_end_VRAM themselves to already be defined
    # upstream (in undefined_syms.init.<version>.txt) before this script
    # runs -- PROVIDE just becomes a no-op for those specific names if they
    # ever show up here.
    for section, root_symbol in [("hd_code", "hd_code_VRAM"), ("hd_front_end", "hd_front_end_VRAM")]:
        if section not in root_addrs:
            continue
        base = root_addrs[section]
        # Fallback only: undefined_syms.init.<version>.txt defines the real,
        # parametric formula (relative to init_VRAM_END) and must be listed
        # before this file's -T so PROVIDE() here is a no-op in practice.
        # Without that upstream definition, this literal (this build's
        # matching address) is what gets used instead.
        out.append(f"PROVIDE({root_symbol} = 0x{base:X});")
        entries = symbols.get(root_symbol, {})
        addr_entries = sorted(
            ((n, v) for n, (k, v) in entries.items() if k == "addr"), key=lambda kv: kv[1]
        )
        size_entries = sorted((n, v) for n, (k, v) in entries.items() if k == "size")

        out.append(f"/* {section} ({len(addr_entries)} symbols, offset from {root_symbol}) */")
        for name, addr in addr_entries:
            offset = addr - base
            if offset < 0:
                out.append(f"PROVIDE({name} = {root_symbol} - 0x{-offset:X});")
            else:
                out.append(f"PROVIDE({name} = {root_symbol} + 0x{offset:X});")
        out.append("")

        if size_entries:
            out.append(f"/* {section} ({len(size_entries)} size constants) */")
            for name, value in size_entries:
                out.append(f"PROVIDE({name} = 0x{value:X});")
            out.append("")

    return "\n".join(out) + "\n"


def main():
    repo_root = Path(__file__).resolve().parent.parent
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--map", type=Path, default=repo_root / "decompressed" / "decompressed.map",
        help="path to decompressed.map",
    )
    parser.add_argument(
        "--out", type=Path, default=repo_root / "exported_symbols.auto.txt",
        help="output linker script path",
    )
    args = parser.parse_args()

    if not args.map.exists():
        print(f"error: {args.map} does not exist (build decompressed/ first)", file=sys.stderr)
        return 1

    root_addrs, symbols = parse_map(args.map)
    missing = [s for s in ("hd_code", "hd_front_end") if s not in root_addrs]
    if missing:
        print(f"error: could not find ADDR(.{missing[0]}) in {args.map}", file=sys.stderr)
        return 1

    args.out.write_text(render(root_addrs, symbols))
    total = sum(len(v) for v in symbols.values())
    print(f"wrote {total} symbols to {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
